#ifndef TENSOR_C_VERSION_H
#define TENSOR_C_VERSION_H

#define TENSOR_C_VERSION_MAJOR 0
#define TENSOR_C_VERSION_MINOR 0
#define TENSOR_C_VERSION_PATCH 1

#define TENSOR_C_VERSION_STRING "0.0.1"

#endif